version: '3'
services:
  proximity:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    user: ${USER_ID:-0}:${GROUP_ID:-0}
    image: proximity:latest
    volumes:
      - ../cards.txt:/app/cardslist       # Volume 1 - Mounts the default 'cards.txt' as cardslist
      - ../run/templates:/app/templates   # Volume 2 - Mounts templates from run/templates (i.e. normal and classic)
      - ../images:/app/images             # Volume 3 - Mounts the output folder
    command: 
      - sh
      - -c
      - java -jar proximity.jar --cards=cardslist --template=normal --use_official_art=true
